site_name: TINZ Docs
site_description: 'Documentation and information about the TINZ'
theme: 'material'

pages:
- Home: index.md
- Reference:
  - 'Board': reference/board.md
  - 'FPGA': reference/fpga.md
  - 'CPU': reference/cpu.md

extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'
  i18n:
    prev: 'Previous'
    next: 'Next'
